In [4]:
#Indexación con arrays de enteros: 
import numpy as np
arr=np.array([10,20,30,40,50,60,70,80,90])
indices=np.array([0,3,5])
seleccion=arr[indices]
print(f"Array original {arr}")
print(f"Elementos seleccionado {seleccion}")

Array original [10 20 30 40 50 60 70 80 90]
Elementos seleccionado [10 40 60]


In [ ]:
#Slicing con matrices Cuando trabajas con arrays de 2 o más dimensiones,
#puedes usar el slicing para obtener sub-matrices o segmentos. La sintaxis
#[inicio:fin:paso] se aplica a cada dimensión, separada por comas. El uso de : solo
#significa "selecciona todo en esta dimensión"
matriz=np.array([[1,2,3],[4,5,6],[7,8,9]])
sub_matriz=matriz[0:2,2]

print(f"matriz origial \n{matriz}\n")
print(f"sub matriz seleccion columnas dos y  filas 0,1 \n{sub_matriz}\n")

matriz origial 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

sub matriz
[3 6]



In [11]:
sub_matriz2=matriz[:,0:2]
print(F"toda la fila y seleccion columna uno y dos\n{sub_matriz2}\n")

toda la fila y seleccion columna uno y dos
[[1 2]
 [4 5]
 [7 8]]



In [13]:
#Elipsis (...): 
#para arrays de alta dimensión, la elipsis ... es un atajo muy útil
#Representa tantos : como sean necesarios para que la expresión de indexación
#sea completa.
arr_3d=np.arange(27).reshape(3,3,3)
sub_array=arr_3d[1,...]
print(f"array original\n{arr_3d}\n")
print(f"sub_array\n{sub_array}\n")

array original
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

sub_array
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]



In [16]:
#2. Manipulación de la Forma (Reshaping)
#El reshaping es el proceso de cambiar las dimensiones de un array. Esto no modifica
#los datos, solo cómo están organizados. (-1) para que array calcule la dimension
arr_plano=np.arange(12)
print(arr_plano)
# Lo transformamos a una matriz de 3 filas y 4 columnas
matriz_3x4=arr_plano.reshape(3,4)
print(f"matroiz por reshape\n{matriz_3x4}\n")



[ 0  1  2  3  4  5  6  7  8  9 10 11]
matroiz por reshape
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]



In [29]:
# Usando -1 para que NumPy calcule una dimensión
matriz4x3=arr_plano.reshape(4,-1)
print(f"\n{matriz4x3}\n")


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]



In [34]:
#flatten() siempre devuelve una copia del array original. Cualquier
#modificación que hagas en el array aplanado no afectará al array original

matriz=np.arange(6).reshape(2,3)
print(f"matriz original\n{matriz}\n")

# Usando flatten() - Crea una copia
copia_plana=matriz.flatten()
print(f"\n{copia_plana}\n")
copia_plana[0]=99
print(f"array original\n {matriz}\n")

matriz original
[[0 1 2]
 [3 4 5]]


[0 1 2 3 4 5]

array original
 [[0 1 2]
 [3 4 5]]



In [36]:
# Usando ravel() - Crea una vista
vista_plana=matriz.ravel()
print(vista_plana)
vista_plana[0]=99
print(f"modifica la matriz\n{matriz}\n")


[0 1 2 3 4 5]
modifica la matriz
[[99  1  2]
 [ 3  4  5]]



In [49]:
import numpy as np
#1. Indexación y Slicing Avanzados 🤔

#1. Selección no contigua:
n10=np.arange(10)
print(n10)
n_seleccion=np.array([0,4,7,8])
select=n10[n_seleccion]
print(f"elementos seleccionado {select}")

[0 1 2 3 4 5 6 7 8 9]
elementos seleccionado [0 4 7 8]


In [51]:
naleatorio=np.random.randint(1,20,size=10)
selnaleatorio=naleatorio[naleatorio>5]
print(f"array original {naleatorio}")
print(f"numero mayores que 5 {selnaleatorio}")

array original [11  6  8 19  2 14 15 10 19  3]
numero mayores que 5 [11  6  8 19 14 15 10 19]


In [66]:
#Rebanadas en 2D: Crea una matriz de 5x5 con números aleatorios.
matriz5x5=np.random.randint(1,20, size=[5,5])
print(f"la matriz original es \n{matriz5x5}\n")

rebanada=matriz5x5[0:5:2,1:4:2]
print(f"sub matriz \n{rebanada}\n")

la matriz original es 
[[12  4 10  3 19]
 [10  3  4  9  6]
 [ 2  5 12 14 15]
 [10  4 17  8  8]
 [ 5  2 19  1 13]]

sub matriz 
[[ 4  3]
 [ 5 14]
 [ 2  1]]



In [78]:
#3. Elipsis (...): Crea un array de 4x4x4.
elip=np.arange(64).reshape(4,4,4)
capa1=elip[1,2,...]
print(f"\n{elip}\n")
print(f"capa 1 es: \n{capa1[2]}\n")


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]

capa 1 es: 
26



In [87]:
#2. Manipulación de la Forma (¡Transformando la información! 💥)
#4. Redimensionar a 2D: Crea un array de 24 elementos
n24=np.arange(24)
print(f"N24 \n{n24}\n")
matriz6x4=n24.reshape(6,4)
print(f"nueva matriz6x4\n{matriz6x4}\n")
#5. Calculando dimensiones: Partiendo del mismo array de 24 elementos, usa -1
matriz3x=n24.reshape(3,-1)
print(f"nueva matriz3x?\n{matriz3x}\n")

matrizcolumna=n24.reshape(-1,4)
print(f"nueva matriz columna 4?\n{matrizcolumna}\n")

N24 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

nueva matriz6x4
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

nueva matriz3x?
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]

nueva matriz columna 4?
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]



In [93]:
#6. flatten vs ravel: Crea una matriz de 3x3. Usa flatten() y modifica el primer
matrix1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"matrix original \n{matrix1}\n")
elemento1=matrix1.flatten()
elemento1[0]=5
print(f"matrix con flatten\n{elemento1}\n")

elemento2=matrix1.ravel()
elemento2[0]=5
print(f"matrix1 \n {matrix1}\n")

matrix original 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

matrix con flatten
[5 2 3 4 5 6 7 8 9]

matrix1 
 [[5 2 3]
 [4 5 6]
 [7 8 9]]

