In [4]:
#Indexación con arrays de enteros: 
import numpy as np
arr=np.array([10,20,30,40,50,60,70,80,90])
indices=np.array([0,3,5])
seleccion=arr[indices]
print(f"Array original {arr}")
print(f"Elementos seleccionado {seleccion}")

Array original [10 20 30 40 50 60 70 80 90]
Elementos seleccionado [10 40 60]


In [ ]:
#Slicing con matrices Cuando trabajas con arrays de 2 o más dimensiones,
#puedes usar el slicing para obtener sub-matrices o segmentos. La sintaxis
#[inicio:fin:paso] se aplica a cada dimensión, separada por comas. El uso de : solo
#significa "selecciona todo en esta dimensión"
matriz=np.array([[1,2,3],[4,5,6],[7,8,9]])
sub_matriz=matriz[0:2,2]

print(f"matriz origial \n{matriz}\n")
print(f"sub matriz seleccion columnas dos y  filas 0,1 \n{sub_matriz}\n")

matriz origial 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

sub matriz
[3 6]



In [11]:
sub_matriz2=matriz[:,0:2]
print(F"toda la fila y seleccion columna uno y dos\n{sub_matriz2}\n")

toda la fila y seleccion columna uno y dos
[[1 2]
 [4 5]
 [7 8]]



In [13]:
#Elipsis (...): 
#para arrays de alta dimensión, la elipsis ... es un atajo muy útil
#Representa tantos : como sean necesarios para que la expresión de indexación
#sea completa.
arr_3d=np.arange(27).reshape(3,3,3)
sub_array=arr_3d[1,...]
print(f"array original\n{arr_3d}\n")
print(f"sub_array\n{sub_array}\n")

array original
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

sub_array
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]



In [16]:
#2. Manipulación de la Forma (Reshaping)
#El reshaping es el proceso de cambiar las dimensiones de un array. Esto no modifica
#los datos, solo cómo están organizados. (-1) para que array calcule la dimension
arr_plano=np.arange(12)
print(arr_plano)
# Lo transformamos a una matriz de 3 filas y 4 columnas
matriz_3x4=arr_plano.reshape(3,4)
print(f"matroiz por reshape\n{matriz_3x4}\n")



[ 0  1  2  3  4  5  6  7  8  9 10 11]
matroiz por reshape
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]



In [29]:
# Usando -1 para que NumPy calcule una dimensión
matriz4x3=arr_plano.reshape(4,-1)
print(f"\n{matriz4x3}\n")


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]



In [34]:
#flatten() siempre devuelve una copia del array original. Cualquier
#modificación que hagas en el array aplanado no afectará al array original

matriz=np.arange(6).reshape(2,3)
print(f"matriz original\n{matriz}\n")

# Usando flatten() - Crea una copia
copia_plana=matriz.flatten()
print(f"\n{copia_plana}\n")
copia_plana[0]=99
print(f"array original\n {matriz}\n")

matriz original
[[0 1 2]
 [3 4 5]]


[0 1 2 3 4 5]

array original
 [[0 1 2]
 [3 4 5]]



In [36]:
# Usando ravel() - Crea una vista
vista_plana=matriz.ravel()
print(vista_plana)
vista_plana[0]=99
print(f"modifica la matriz\n{matriz}\n")


[0 1 2 3 4 5]
modifica la matriz
[[99  1  2]
 [ 3  4  5]]



In [49]:
import numpy as np
#1. Indexación y Slicing Avanzados 🤔

#1. Selección no contigua:
n10=np.arange(10)
print(n10)
n_seleccion=np.array([0,4,7,8])
select=n10[n_seleccion]
print(f"elementos seleccionado {select}")

[0 1 2 3 4 5 6 7 8 9]
elementos seleccionado [0 4 7 8]


In [51]:
naleatorio=np.random.randint(1,20,size=10)
selnaleatorio=naleatorio[naleatorio>5]
print(f"array original {naleatorio}")
print(f"numero mayores que 5 {selnaleatorio}")

array original [11  6  8 19  2 14 15 10 19  3]
numero mayores que 5 [11  6  8 19 14 15 10 19]


In [66]:
#Rebanadas en 2D: Crea una matriz de 5x5 con números aleatorios.
matriz5x5=np.random.randint(1,20, size=[5,5])
print(f"la matriz original es \n{matriz5x5}\n")

rebanada=matriz5x5[0:5:2,1:4:2]
print(f"sub matriz \n{rebanada}\n")

la matriz original es 
[[12  4 10  3 19]
 [10  3  4  9  6]
 [ 2  5 12 14 15]
 [10  4 17  8  8]
 [ 5  2 19  1 13]]

sub matriz 
[[ 4  3]
 [ 5 14]
 [ 2  1]]



In [78]:
#3. Elipsis (...): Crea un array de 4x4x4.
elip=np.arange(64).reshape(4,4,4)
capa1=elip[1,2,...]
print(f"\n{elip}\n")
print(f"capa 1 es: \n{capa1[2]}\n")


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]

capa 1 es: 
26



In [87]:
#2. Manipulación de la Forma (¡Transformando la información! 💥)
#4. Redimensionar a 2D: Crea un array de 24 elementos
n24=np.arange(24)
print(f"N24 \n{n24}\n")
matriz6x4=n24.reshape(6,4)
print(f"nueva matriz6x4\n{matriz6x4}\n")
#5. Calculando dimensiones: Partiendo del mismo array de 24 elementos, usa -1
matriz3x=n24.reshape(3,-1)
print(f"nueva matriz3x?\n{matriz3x}\n")

matrizcolumna=n24.reshape(-1,4)
print(f"nueva matriz columna 4?\n{matrizcolumna}\n")

N24 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

nueva matriz6x4
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

nueva matriz3x?
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]

nueva matriz columna 4?
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]



In [6]:
#6. flatten vs ravel: Crea una matriz de 3x3. Usa flatten() y modifica el primer
matrix1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"matrix original \n{matrix1}\n")
elemento1=matrix1.flatten()
elemento1[0]=5
print(f"matrix con flatten\n{elemento1}\n")

elemento2=matrix1.ravel()
elemento2[0]=5
print(f"matrix1 \n {matrix1}\n")

matrix original 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

matrix con flatten
[5 2 3 4 5 6 7 8 9]

matrix1 
 [[5 2 3]
 [4 5 6]
 [7 8 9]]



In [14]:
#np.concatenate(): Es la función más versátil. Te permite unir arrays a lo largo de
#un eje (axis) específico
import numpy as np
a=([[1,2],[3,4]])
b=([[5,6]])
# Unir verticalmente (por defecto o axis=0)
c_vertical=np.concatenate((a,b),axis=0)
print(f"Union vertical\n{c_vertical}\n")
# Unir horizontalmente (axis=1), requiere que las formas coincidan en el otro eje # Hacemos la transpuesta para que la forma sea (2, 1)
transpuesta=np.transpose(b)  #cuando tengo una dimension
c_horizontal=np.concatenate((a,transpuesta),axis=1)
print(f"union horizontal{transpuesta}")
                    

Union vertical
[[1 2]
 [3 4]
 [5 6]]

union horizontal[[5]
 [6]]


In [23]:
#np.split(): Divide un array en múltiples sub-arrays iguales.
arr=np.arange(16).reshape(4,4)
print(f"array original a dividir \n{arr}\n")
dividir=np.split(arr,2,axis=0)# Dividimos en 2 partes por las filas
print(f"visualizacion parte 1\n{dividir[0]}\n")
print(f"visualizacion parte 1\n{dividir[1]}\n")

array original a dividir 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

visualizacion parte 1
[[0 1 2 3]
 [4 5 6 7]]

visualizacion parte 1
[[ 8  9 10 11]
 [12 13 14 15]]



In [ ]:
#4. Broadcasting 📡
import numpy as np
matriz=([[1,2,3],[4,5,6]])
vector=([[10,11,12]])
resultado=matriz+vector
print(f"Resultado \n{resultado}\n")


Resultado 
[[1, 2, 3], [4, 5, 6], [10, 11, 12]]



In [ ]:
#3. El broadcasting es posible si para cada dimensión, las formas son iguales o
una de ellas es 1.
import numpy as np
matriz = np.array([[1, 2, 3],
[4, 5, 6]])
vector = np.array([10, 20, 30])
# El vector [10, 20, 30] se "estira" para sumarse a cada fila de la matriz
resultado = matriz + vector
print(f"Matriz:\n{matriz}")
print(f"\nVector: {vector}")
print(f"\nResultado del broadcasting:\n{resultado}")
# Resultado: [[11 22 33], [14 25 36]]


In [28]:
#5. Mascaramiento Booleano (Boolean Masking) 🎭
import numpy as np
data=np.array([5,15,52,98,10,56,789,52,14,75,63,95,20])
mascara=data>30
print(f"array original\n{data}\n")
print(f"mascaca \n{mascara}\n")

array original
[  5  15  52  98  10  56 789  52  14  75  63  95  20]

mascaca 
[False False  True  True False  True  True  True False  True  True  True
 False]



In [29]:
# Usamos la máscara para filtrar el array
valores_filtrado=data[mascara]
print(f"los valores filtrado son\n {valores_filtrado}\n")

los valores filtrado son
 [ 52  98  56 789  52  75  63  95]



In [30]:
#Filtremos por un rango! Valores entre 20 y 70
datos_filtrado=(data>20)&(data<70)
datos_elegidos=data[datos_filtrado]
print(f"datos elegido\n{datos_elegidos}\n")

datos elegido
[52 56 52 63]



In [33]:
#. Broadcasting (¡Multiplicando la diversión! 🤩)
#10. Suma de vector a matriz: Crea una matriz de 3x3 y un vector de 3 elementos
matriz=np.array([[1,2,3],[4,5,6],[7,8,9]])
vector=np.array([[10,20,30]])
producto=matriz+vector
print(f"La suma de la matrix es \n{producto}\n")

La suma de la matrix es 
[[11 22 33]
 [14 25 36]
 [17 28 39]]



In [36]:
#11. Multiplicación por un escalar: Crea un array de 5 elementos. 
elemento5=np.arange(5)*10
print(f"elemento x 10\n{elemento5}\n")

elemento x 10
[ 0 10 20 30 40]



In [42]:
#12. Broadcasting con columnas: Crea una matriz de 3x4 y otra de 3x1. 
max3x4=np.arange(12).reshape(3,4)
max3x1=np.arange(3).reshape(3,1)
Sumo=max3x4 + max3x1
print(f"matriz\n{max3x4}\n")
print(f"Suma de matrix por Broadcasting \n{Sumo}\n")


matriz
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Suma de matrix por Broadcasting 
[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]]



In [59]:
#5. Mascaramiento Booleano (¡Filtrando la información clave! 🕵️‍♀️ )
#13. Filtro simple: Crea un array de 20 números aleatorios entre 1 y 100
N20=np.random.randint(1,100,size=20)
filtradro=(N20>75)
filtradro75=N20[filtradro]
print(f"Filtrado mayor de 75\n{filtradro75}\n")



Filtrado mayor de 75
[88 93]



In [60]:
#14. Filtro de rango:
filtrado2=(N20>30)&(N20<60)
filtrado20_60=N20[filtrado2]
print(f"filtrado en rango\n{filtrado20_60}\n")

filtrado en rango
[50 43 54 45 39 44 47 31]



In [65]:
#15. Combinando condiciones:
primer_filtrado= (N20%2==0) & (N20>90)
combinacion=N20[primer_filtrado]
print(f"combinacion \n{combinacion}\n")

combinacion 
[]



In [93]:
#Sección 2: Problemas Combinados (¡El desafío final! 🤯)
#Análisis de datos simulados:
n100=np.random.randint(1,200,size=100)
mascara5=(n100%5==0) & (n100<100)
try:
    valores_seleccionados=n100[mascara5].reshape(2,-1)
except ValueError:
    print("Error en el calculo de la matriz")
print(f"valores selecionados\n{valores_seleccionados}\n")


Error en el calculo de la matriz
valores selecionados
[[35 35 10 20]
 [50 55 80 45]]



In [116]:
#2. Preparación para Machine Learning
matriz10x3=np.random.randint(1,40,size=[10,3])
print(f"\n{matriz10x3}\n")
matriz8=matriz10x3[:8]
matriz2=matriz10x3[8:10]
print(f"\n{matriz8}\n")
print(f"\n{matriz2}\n")



[[30 38  6]
 [23  6 12]
 [27  1 24]
 [29 14 22]
 [ 6  1 23]
 [27  6  3]
 [23 10 36]
 [29 25 14]
 [17 12 36]
 [16  5 21]]


[[30 38  6]
 [23  6 12]
 [27  1 24]
 [29 14 22]
 [ 6  1 23]
 [27  6  3]
 [23 10 36]
 [29 25 14]]


[[17 12 36]
 [16  5 21]]



In [119]:
#Después, toma el conjunto de las 8 filas y divídelo de nuevo en dos
#matrices, una con las primeras dos columnas y otra con la última.
matrizc2=matriz8[:,0:2]
matrizc3=matriz8[:,2:3]
print(f"\n{matrizc2}\n")
print(f"\n{matrizc3}\n")


[[30 38]
 [23  6]
 [27  1]
 [29 14]
 [ 6  1]
 [27  6]
 [23 10]
 [29 25]]


[[ 6]
 [12]
 [24]
 [22]
 [23]
 [ 3]
 [36]
 [14]]



In [ ]:
#3. Procesamiento de píxeles: 
n50=np.random.randint(0,255,size=[50,50])
print(f"Matriz50x50 Original\n {n50}\n")


Matriz50x50 Original
 [[170  64 210 ... 204  89  15]
 [ 45  21  32 ...  54  46 117]
 [109 120 218 ...  31 159  36]
 ...
 [ 87 191 103 ... 177 231 216]
 [172 249  66 ...  90 155 254]
 [  6  80  64 ...  57 161 124]]



In [138]:
grises_claros=(n50>150) & (n50<200)
mascara=n50[grises_claros]+50
print(f"valores grises claros \n{mascara}\n")

valores grises claros 
[220 231 209 227 234 204 226 230 202 238 207 233 215 213 215 224 212 245
 219 246 237 233 243 224 209 230 228 218 225 208 214 229 208 245 219 221
 225 248 238 235 244 202 217 206 211 246 237 237 215 219 234 205 214 216
 220 233 233 244 245 223 218 244 232 225 207 218 215 234 208 246 238 223
 218 241 241 214 220 213 238 201 219 235 202 215 212 217 236 238 222 225
 212 223 208 219 236 239 237 223 221 223 238 225 212 245 244 241 216 233
 235 224 240 213 242 232 207 238 221 242 244 220 227 238 244 239 222 245
 233 248 231 215 225 225 212 246 219 207 210 205 232 224 249 228 213 242
 219 215 209 231 231 214 236 234 239 205 242 207 209 235 229 249 219 218
 225 236 211 229 206 214 240 207 226 244 227 214 218 223 240 205 223 235
 216 219 224 231 239 212 244 217 249 208 215 235 237 232 217 215 224 204
 205 205 225 217 215 210 237 235 236 249 239 208 201 206 220 232 236 204
 219 203 244 229 241 243 209 214 220 213 225 202 239 247 249 239 207 225
 229 215 214 242 243 226 212