In [1]:
import numpy as np


In [2]:

matriz_cero_3x3=np.random.randint(1,101,size=[3,3])
print(f"matriz modificada \n{matriz_cero_3x3}\n")
extraccion_ultima_fila=matriz_cero_3x3[1:,]
print(extraccion_ultima_fila)
print(f"Elemento en la esquina inferior derecha {matriz_cero_3x3[2,2]}")


matriz modificada 
[[19 99 83]
 [83 65 70]
 [71 84 22]]

[[83 65 70]
 [71 84 22]]
Elemento en la esquina inferior derecha 22


In [3]:
#➕ Operaciones Vectorizadas en NumPy
#Crea un array de 10 elementos que vaya de 0 a 9.
n_10=np.arange(10)
#Multiplica cada elemento del array por 2
n_2x10=2*n_10
#Suma 5 a cada elemento del array resultante
n_suma5=5+n_2x10
print(f" vector original\n{n_10}\n")
print(f"multiplicacion de los elemento por 2:\n{n_2x10}\n")
print(f"suma 5 al resultado final\n{n_suma5}\n")

 vector original
[0 1 2 3 4 5 6 7 8 9]

multiplicacion de los elemento por 2:
[ 0  2  4  6  8 10 12 14 16 18]

suma 5 al resultado final
[ 5  7  9 11 13 15 17 19 21 23]



In [4]:
#3. 🔎 Indexación Condicional con NumPy
# Crea un array de 15 números enteros aleatorios entre 1 y 20
n_ale_enteros=np.random.randint(1,20,size= 15)
#Usa indexación booleana para encontrar y mostrar solo los números que sean
#mayores que 10
n_10=n_ale_enteros[n_ale_enteros>10]

print(f"numero mayores que 10 en el array \n{n_10}\n")


numero mayores que 10 en el array 
[17 18 19 11 14]



In [5]:
#Parte 1: Creación y Manipulación de Arrays ✨
#Array de Zeros: Crea un array de 3×3 lleno de ceros
m3x3=np.zeros((3,3)) #usar doble parentesis
print(f"\n{m3x3}\n")

#Array de Unos: Crea un array de 5×5 lleno de unos
m5x5=np.ones((5,5))
print(f"\n{m5x5}\n")

#Array con Rango: Crea un array que contenga los números del 10 al 20,
#excluyendo el 20
n_10_al_20=np.arange(10,20)
print(f"\n{n_10_al_20}\n")

#Matriz Identidad: Crea una matriz identidad de 4×4.
matriz_iden=np.identity(4)
print(f"matriz identidad \n{matriz_iden}\n")



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[10 11 12 13 14 15 16 17 18 19]

matriz identidad 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]



In [6]:
#Array Aleatorio: Crea un array de 3×3 con números enteros aleatorios entre 1 y
#100.
ale3x3=np.random.randint(1,100, size=[3,3])
print(f"matriz aleatoria \n{ale3x3}\n")

#Redimensionar: Crea un array unidimensional con 15 elementos y
#redimensiónalo a una matriz de 3×5
m_original=np.arange(15)
m_3x5=m_original.reshape(3,5)
print(m_original)
print(f"matriz nueva 3x5\n {m_3x5}\n")

matriz aleatoria 
[[33 29 64]
 [58 68 42]
 [92 10 30]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
matriz nueva 3x5
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]



In [7]:
#Concatenar Arrays: Crea dos arrays, y concaténalos horizontalmente
a=np.array([1,2,3])
b=np.array([4,5,6])
conta=np.concatenate([a,b])
con=np.hstack([a,b])
print(conta)
print(con)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [28]:
#Parte 2: Indexación y Operaciones 🎯
#8. Selección de Fila y Columna:"
#Dada la matriz matriz = np.arange(1,26).reshape(5, 5), selecciona la tercera fila completa y la cuarta columna
matriz_matriz=np.arange(1,26).reshape(5,5)
print(f"matriz inicial\n{matriz_matriz}\n")
print(f"selecionala la tecera fila \n{matriz_matriz[2]}\n")
print(f"selecionala la cuarta columna \n{matriz_matriz[:,3]}\n")


matriz inicial
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

selecionala la tecera fila 
[11 12 13 14 15]

selecionala la cuarta columna 
[ 4  9 14 19 24]



In [36]:
#9 Selección con Slicing
#De la misma matriz, selecciona el subconjunto de datos
#que va de la segunda a la cuarta fila y de la segunda a la cuarta columna
matriz_matriz=np.arange(1,26).reshape(5,5)
sub_matriz=matriz_matriz[1:4,1:4]
print(f"matriz inicial\n{matriz_matriz}\n")
print(f"de \n{sub_matriz}\n")


matriz inicial
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

de 
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]



In [37]:
#10. Indexación Booleana: De la matriz, selecciona todos los elementos que sean
#mayores que 15
mayor_que15=matriz_matriz[matriz_matriz>15]
print(f"matrizz mayot que 15\n{mayor_que15}\n")

matrizz mayot que 15
[16 17 18 19 20 21 22 23 24 25]



In [ ]:
#Suma de Filas: Calcula la suma de cada fila de la matriz.
print(f"suma de la fila de la matriz {sum(matriz_matriz[0])}")
print(f"suma de la fila de la matriz {sum(matriz_matriz[1])}")
print(f"suma de la fila de la matriz {sum(matriz_matriz[2])}")
print(f"suma de la fila de la matriz {sum(matriz_matriz[3])}")
print(f"suma de la fila de la matriz {sum(matriz_matriz[4])}")

print(f"suma de la fila de la matriz\n {matriz_matriz.sum(axis=1)} \n") #suma fila axis =1

suma de la fila de la matriz 15
suma de la fila de la matriz 40
suma de la fila de la matriz 65
suma de la fila de la matriz 90
suma de la fila de la matriz 115
suma de la fila de la matriz
 [ 15  40  65  90 115] 



In [ ]:
#12. Suma de Columnas: Calcula la suma de cada columna de la matriz.
print(f"suma columna \n{matriz_matriz.sum(axis=0)}") #suma columna

suma columna 
[55 60 65 70 75]


In [55]:
#Producto de Elementos: Calcula el producto de todos los elementos de la
#matriz.
producto_toda_la_matriz=matriz_matriz.prod(axis=1)
print(f"multiplicacion de la matriz {producto_toda_la_matriz}")

multiplicacion de la matriz [    120   30240  360360 1860480 6375600]


In [66]:
#14  Sustitución de Valores: Reemplaza todos los números impares de la matriz por
#el valor -
print("-+-" * 20)
# --- Paso 1: Crear la máscara booleana ---
# La condición "es impar" se puede expresar como "el resto de la división por 2 es diferente de cero".
# Esto crea una nueva matriz del mismo tamaño, con 'True' donde el número es impar.
numero_impares=matriz_matriz % 2 !=0
print(numero_impares)

#Paso 2: Usar la máscara para sustituir valores ---
# Ahora usamos la máscara para seleccionar todos los elementos donde el valor es 'True'
# y les asignamos el nuevo valor, que en este caso es -1.
matriz_matriz[numero_impares]=-1
print(f"matriz con numero -1\n{matriz_matriz}\n")

-+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-
[[ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]]
matriz con numero -1
[[-1  2 -1  4 -1]
 [ 6 -1  8 -1 10]
 [-1 12 -1 14 -1]
 [16 -1 18 -1 20]
 [-1 22 -1 24 -1]]



In [70]:
#Parte 3: Funciones Estadísticas y Avanzadas 📈
#15. Valor Máximo y Mínimo: Encuentra el valor máximo y mínimo de la matriz
print(f"maximo valor {matriz_matriz.max()}")
print(f"maximo valor {matriz_matriz.min()}")

maximo valor 24
maximo valor -1


In [72]:
#16. Media y Desviación Estándar: Calcula la media y la desviación estándar de la
#matriz
print(f" la media es {matriz_matriz.mean()}")
print(f"desviacion standar {matriz_matriz.std()}")

 la media es 5.72
desviacion standar 8.473582477323273


In [73]:
#Array Único: Dado el array arr = np.array([1, 2, 1, 3, 4, 3, 5]), encuentra los
#elementos únicos. con unique(
unicos=np.unique(matriz_matriz)
print(f"elemento unicoss \n{unicos}")


elemento unicoss 
[-1  2  4  6  8 10 12 14 16 18 20 22 24]


In [ ]:
#18. Ordenar Array: Crea un array de 10 números aleatorios y ordénalo de menor a
#mayor
bien =np.random.randint(1,10,size=10)
orden=np.sort(bien)
print(f"orden de numero{orden}")
# Puedes invertir el array ordenado usando la sintaxis [::-1].

orden de numero[1 4 4 4 5 6 6 7 7 9]


In [91]:
#19. Transponer Matriz: Transpón la matriz
matrizU=np.random.randint(1,10,size=[3,4])
print(f"matriz original\n{matrizU}\n")
tran=matrizU.T
print(f"matriz transpuesta\n {tran}\n")

matriz original
[[5 1 7 4]
 [1 6 7 5]
 [5 2 1 1]]

matriz transpuesta
 [[5 1 5]
 [1 6 2]
 [7 7 1]
 [4 5 1]]



In [96]:
#20. Normalización (Z-Score): Crea un array de 10 números aleatorios y normaliza
#sus valores usando la fórmula Z=(X−μ)/σ
n10=np.random.randint(1,50,size=10)
print(n10)

# 2. Calcula la media (μ) y la desviación estándar (σ) del array.
# np.mean() calcula el promedio de todos los elementos.

media=np.mean(n10)
desviacion_estandar=np.std(n10)
#normalizacion de la desviacion standar 
Z_estandar=(desviacion_estandar-media)/desviacion_estandar
print(f" La normalizacion de la desviacion estandar {Z_estandar:.2f}")
Z_media=(media-media)/desviacion_estandar
print(f" La normalizacion de la desviacion estandar {Z_media:.2f}")



[ 5 32  1 27 19 26  9 43 46 32]
 La normalizacion de la desviacion estandar -0.65
 La normalizacion de la desviacion estandar 0.00
