In [37]:
import numpy as np


In [38]:

matriz_cero_3x3=np.random.randint(1,101,size=[3,3])
print(f"matriz modificada \n{matriz_cero_3x3}\n")
extraccion_ultima_fila=matriz_cero_3x3[1:,]
print(extraccion_ultima_fila)
print(f"Elemento en la esquina inferior derecha {matriz_cero_3x3[2,2]}")


matriz modificada 
[[84 48 12]
 [81 96 15]
 [48 53 41]]

[[81 96 15]
 [48 53 41]]
Elemento en la esquina inferior derecha 41


In [39]:
#➕ Operaciones Vectorizadas en NumPy
#Crea un array de 10 elementos que vaya de 0 a 9.
n_10=np.arange(10)
#Multiplica cada elemento del array por 2
n_2x10=2*n_10
#Suma 5 a cada elemento del array resultante
n_suma5=5+n_2x10
print(f" vector original\n{n_10}\n")
print(f"multiplicacion de los elemento por 2:\n{n_2x10}\n")
print(f"suma 5 al resultado final\n{n_suma5}\n")

 vector original
[0 1 2 3 4 5 6 7 8 9]

multiplicacion de los elemento por 2:
[ 0  2  4  6  8 10 12 14 16 18]

suma 5 al resultado final
[ 5  7  9 11 13 15 17 19 21 23]



In [ ]:
#3. 🔎 Indexación Condicional con NumPy
# Crea un array de 15 números enteros aleatorios entre 1 y 20
n_ale_enteros=np.random.randint(1,20,size= 15)
#Usa indexación booleana para encontrar y mostrar solo los números que sean
#mayores que 10
n_10=n_ale_enteros[n_ale_enteros>10]

print(f"numero mayores que 10 en el array \n{n_10}\n")


array originaal
[18 15 17 16  5 15  2 12 19  5  4  9  5  8 19]

numero mayores que 10 en el array 
[18 15 17 16 15 12 19 19]



In [50]:
#Parte 1: Creación y Manipulación de Arrays ✨
#Array de Zeros: Crea un array de 3×3 lleno de ceros
m3x3=np.zeros((3,3)) #usar doble parentesis
print(f"\n{m3x3}\n")

#Array de Unos: Crea un array de 5×5 lleno de unos
m5x5=np.ones((5,5))
print(f"\n{m5x5}\n")

#Array con Rango: Crea un array que contenga los números del 10 al 20,
#excluyendo el 20
n_10_al_20=np.arange(10,20)
print(f"\n{n_10_al_20}\n")

#Matriz Identidad: Crea una matriz identidad de 4×4.
matriz_iden=np.identity(4)
print(f"matriz identidad \n{matriz_iden}\n")



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[10 11 12 13 14 15 16 17 18 19]

matriz identidad 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]



In [56]:
#Array Aleatorio: Crea un array de 3×3 con números enteros aleatorios entre 1 y
#100.
ale3x3=np.random.randint(1,100, size=[3,3])
print(f"matriz aleatoria \n{ale3x3}\n")

#Redimensionar: Crea un array unidimensional con 15 elementos y
#redimensiónalo a una matriz de 3×5
m_original=np.arange(15)
m_3x5=m_original.reshape(3,5)
print(m_original)
print(f"matriz nueva 3x5\n {m_3x5}\n")

matriz aleatoria 
[[94 41 52]
 [ 7 19 87]
 [55  8 18]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
matriz nueva 3x5
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]



In [73]:
#Concatenar Arrays: Crea dos arrays, y concaténalos horizontalmente
a=np.array([1,2,3])
b=np.array([4,5,6])
conta=np.concatenate([a,b])
con=np.hstack([a,b])
print(conta)
print(con)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
#Parte 2: Indexación y Operaciones 🎯