In [1]:
# Crear un vector 1D de enteros

import numpy as np
lista_1d=[1,2,3,4]
vector=np.array(lista_1d)
print(f"vector:\n{vector}\n") #sale el nombe vector y debajo los datos
print(vector.dtype)

vector:
[1 2 3 4]

int64


In [3]:
# Crear una matriz 2D de punto flotante
lista_2d=[[1.0,2.0,3.0],[4.0,5.0,6.0]]
matriz=np.array(lista_2d)
print(f"matriz:\n{matriz}\n")
print(f"La forma de la matriz es:{matriz.shape}") #indica la cantidad de filas y columna de la matriz
print(f"tipo de datos{matriz.dtype}") #dtype indica el tipo de datos este caso flotante


matriz:
[[1. 2. 3.]
 [4. 5. 6.]]

La forma de la matriz es:(2, 3)
tipo de datosfloat64


In [4]:
#Arrays de Ceros y Unos:
# Array de ceros de 3x4
ceros=np.zeros((3,4))
print(f"Array Ceros:\n {ceros}  \n")

Array Ceros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]  



In [5]:
# Array de unos de 5 elementos, con tipo de dato entero
unos=np.ones(5,dtype=np.int64)
print(f"Array unos:\n{unos}\n")

Array unos:
[1 1 1 1 1]



In [7]:
# Rangos Numéricos: Crea secuencias de números de forma automática
rango_escalar=np.arange(0,10,2) # De 0 a 10 (excluido), paso de 2
print(f"array con no.arange\n{rango_escalar}\n")

array con no.arange
[0 2 4 6 8]



In [ ]:
# Números espaciados uniformemente
# 5 puntos desde 0 hasta 1 (incluidos)
lineal=np.linspace(0,1,5)
print(f"Array con np.lispace:\n{lineal}\n") #ideal para sistema de coordenadas


Array con np.lispace:
[0.   0.25 0.5  0.75 1.  ]



In [8]:
#Arrays Aleatorios: NumPy tiene un módulo random muy completo
# Matriz 2x2 de números aleatorios entre 0 y 1 (distribución uniforme
aleatorio=np.random.rand(3,3)
print(f"Matriz Aleatoria uniforme:\n{aleatorio}\n")


Matriz Aleatoria uniforme:
[[0.15908873 0.5198544  0.2965352 ]
 [0.884016   0.66000499 0.25585667]
 [0.06959604 0.31411654 0.32427348]]



In [48]:
# Enteros aleatorios en un rango (de 1 a 10, tamaño 3)
enteros_aleatorio=np.random.randint(1,10,size=3) #busca enteros aleatorios la cantidad depende de size
print(f"Enteros aleatorios\n{enteros_aleatorio}\n")

Enteros aleatorios
[9 6 3]



In [15]:
# Números de una distribución normal estándar
normal=np.random.randn(2,3) #toam cualquier entero
print(f"Matriz normal \n{normal}\n")

Matriz normal 
[[ 0.16286721  0.60623762 -1.8408489 ]
 [-2.54769845 -0.10471996  0.65755522]]



In [22]:
#Indexación Básica: Se accede a los elementos usando los índices entre
#,corchetes, separados por comas para cada dimensión
matriz_1=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(f"matriz original:\n{matriz_1}\n")
# Acceder a un solo elemento (fila 1, columna 2)
print(f"elemento en [1,2] = {matriz_1[1,2]}\n")

# Modificar un elemento
matriz_1[1,2]=90
print(f"matriz modificada\n{matriz_1}\n")

matriz original:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

elemento en [1,2] = 60

matriz modificada
[[10 20 30]
 [40 50 90]
 [70 80 90]]



In [44]:
#Slicing (Corte): Extrae un sub-array de un array existente. La sintaxis
#[inicio:fin:paso] es la misma que en las listas, pero aplicada a cada dimensión

# Todas las filas, pero solo la columna 0 y1
sub_matriz=matriz_1[:,0:2]
print(f"sub matriz columna (0,1) \n{sub_matriz}\n")


sub matriz columna (0,1) 
[[10 20]
 [40 50]
 [70 80]]



In [52]:
## Filas 0 y 1, pero todas las columnas
sub_matriz_2=matriz_1[0:2,:]
print(f"sub matriz fila (0,2)\n{sub_matriz_2}\n")

# Seleccionar la última fila
print(f"seleccon ulima fila \n{matriz_1[-1,:]}")

sub matriz fila (0,2)
[[10 20 30]
 [40 50 90]]

seleccon ulima fila 
[70 80 90]


In [4]:
import numpy as np
## Crear un vector 1D de enteros
lista_1d=[1,22,36,1.4,256]
vector_1d=np.array(lista_1d)
print(f"vector_1d \n{vector_1d}\n")

vector_1d 
[  1.   22.   36.    1.4 256. ]



In [5]:
# Crear una matriz 2D de punto flotante
lista_2d=[[1.4,52,36,0.26],[0,12.3,56,0]]
matriz=np.array(lista_2d)
print(f"matriz\n{matriz}\n")
print(f"la forma de la matriz {matriz.shape}")
print(f"tipo de datos de la matriz {matriz.dtype}")

matriz
[[ 1.4  52.   36.    0.26]
 [ 0.   12.3  56.    0.  ]]

la forma de la matriz (2, 4)
tipo de datos de la matriz float64


In [6]:
# Array de ceros de 3x4
ceros=np.zeros((3,4))
print(f"matriz ceros \n{ceros}\n")

matriz ceros 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]



In [7]:
# Array de unos de 5 elementos, con tipo de dato entero
unos=np.ones(5,dtype=np.int64)
print(f"matriz unos\n{unos}\n")

matriz unos
[1 1 1 1 1]



In [8]:
#Rangos Numéricos: Crea secuencias de números de forma automática.
# Como range() de Python, pero crea un array
rango_escalar=np.arange(0,20,2)
print(f"array np.arange\n{rango_escalar}\n")

array np.arange
[ 0  2  4  6  8 10 12 14 16 18]



In [9]:
# Números espaciados uniformemente
# 5 puntos desde 0 hasta 1 (incluidos)
lineal=np.linspace(0,1,5)
print(f"Array con np.linspace {lineal}")

Array con np.linspace [0.   0.25 0.5  0.75 1.  ]


In [12]:
#Arrays Aleatorios:
# Matriz 2x2 de números aleatorios entre 0 y 1 (distribución uniforme)
aleatorio=np.random.rand(2,2)
print(f"matriz aleatoria 0-1 \n{aleatorio}\n")

matriz aleatoria 0-1 
[[0.17533641 0.03594699]
 [0.63661596 0.80908173]]



In [ ]:
# Enteros aleatorios en un rango (de 1 a 10, tamaño 3)
enteros_aleatorio = np.random.randint(1, 10, size=3)
print(f"matriz de enteros aleatorio\n {enteros_aleatorio}\n")

matriz de enteros aleatorio
 [5 5 5]



In [22]:
# Números de una distribución normal estándar
normal=np.random.randn(2,2)
print(f"matriz distroibucion normal\n{normal}\n")

matriz distroibucion normal
[[-0.30801632  1.2293122 ]
 [-0.83102972  1.23955049]]



In [25]:
#3. Indexación y Slicing: Navegando tus Datos 🗺
#Indexación Básica
matriz=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(f"print matriz original\n{matriz}\n")


print matriz original
[[10 20 30]
 [40 50 60]
 [70 80 90]]



In [26]:
# Acceder a un solo elemento (fila 1, columna 2)
print(f"acceso elemento fila 1 columna 2 \n{matriz[1,2]}\n")

acceso elemento fila 1 columna 2 
60



In [28]:
# Modificar un elemento
matriz[1,2]=99
print(f"elemento modificado fila uno columna 2\n{matriz}\n")

elemento modificado fila uno columna 2
[[10 20 30]
 [40 50 99]
 [70 80 90]]



In [29]:
#Slicing (Corte): Extrae un sub-array de un array existente
# [inicio:fin:paso] es la misma que en las listas, pero aplicada a cada dimensión
# Todas las filas, pero solo la columna 0 y 1
sub_matriz=matriz[:,0:2]
print(f"sub matriz\n{sub_matriz}\n")

sub matriz
[[10 20]
 [40 50]
 [70 80]]



In [32]:
# Filas 0 y 1, pero todas las columnas
sub_matriz_2=matriz[0:2,:]
print(f"muuestra fila 0 y 1 y todas la columnas \n {sub_matriz_2}\n")

muuestra fila 0 y 1 y todas la columnas 
 [[10 20 30]
 [40 50 99]]



In [34]:
#selecciona la ultima fila
sub_matriz_3=matriz[-1,:]
print(f"ultima fila \n{sub_matriz_3}\n")

ultima fila 
[70 80 90]



In [41]:
#Indexación Booleana
#Esta es una de las características más potentes. Te
#permite seleccionar elementos basándose en una condición lógica. Esto es
#extremadamente útil para filtrar datos que cumplen ciertos criterios.
# Seleccionar todos los elementos mayores a 50
mayores_que50=matriz[matriz>50]
print(f"mayores que 50\n{mayores_que50}\n")
# Esto devuelve un array plano (1D) con los valores que cumplen la condición.

mayores que 50
[99 70 80 90]



In [43]:
#Operaciones Vectorizadas y Matriciales: La Magia de NumPy
#Operaciones Elemento por Elemento: Aplican la operación a cada par de
#elementos correspondientes en los arrays. La "magia" es que no necesitas un for
# loop
a=np.array([1,2,3])
b=np.array([10,20,30])
print(f"Suma a+b\n{a+b}\n")
print(f"multiplicacon\n{a*b}\n")

Suma a+b
[11 22 33]

multiplicacon
[10 40 90]



In [45]:
#Funciones Universales (ufuncs): NumPy incluye una vasta colección de
#funciones matemáticas que operan sobre arrays. Estas funciones son
#optimizadas y se aplican a cada elemento
array_ejemplo=np.array([0,np.pi/2,np.pi])
print(f"el seno de cada elemento es\n{np.sin(array_ejemplo)}\n") 
# np.sin es una ufunc

array_log=np.array([1,np.e,np.e**2])
print(f"el logaritno nepeniano \n{np.log(array_log)}\n")

el seno de cada elemento es
[0.0000000e+00 1.0000000e+00 1.2246468e-16]

el logaritno nepeniano 
[0. 1. 2.]



In [48]:
#Operaciones de Agregación (Funciones de Resumen): Permiten obtener
#rápidamente estadísticas de tus datos. El argumento axis es clave para
#especificar la dirección de la operación

matriz_ejempo=([1,2,3],[4,5,6])
print(f"suma todo los elementos de la matriz\n{np.sum(matriz_ejempo)}\n")
print(f"Valor maximo de la matriz\n{np.max(matriz_ejempo)}\n valor minimo\n{np.min(matriz_ejempo)}\n")
print(f"Valor promedio de la matriz \n{np.mean(matriz_ejempo)}\n")

suma todo los elementos de la matriz
21

Valor maximo de la matriz
6
 valor minimo
1

Valor promedio de la matriz 
3.5



In [49]:
# Suma por columna (axis=0): 'colapsa' el array verticalmente
print(f"suma por columna\n{np.sum(matriz_ejempo,axis=0)}")

suma por columna
[5 7 9]


In [50]:
#Multiplicación Matricial: Fundamental para el álgebra lineal y el machine
#learning. Se diferencia de la multiplicación elemento por elemento.
matriz_A=np.array([[1,2],[3,4]])
matriz_B=np.array([[5,6],[7,8]])
# Multiplicación matricial con el operador @
resultados_dot=matriz_A @ matriz_B
print(f"multiplicacion de matrices por @ \n{resultados_dot}\n")

multiplicacion de matrices por @ 
[[19 22]
 [43 50]]



In [ ]:
#5. Reshaping y Broadcasting: Flexibilidad y Potencia 💡
#Reshaping (Cambio de Forma)Te permite cambiar las dimensiones de un array
#sin alterar sus datos. Esto es crucial para preparar los datos para diferentes
#algoritmos que requieren una forma específica
vector_2d=np.arange(9)
print(f"vector original \n{vector_2d}\n")
#convertir en una matriz 3x3
matriz_3x3=vector_2d.reshape(3,3)
print(f"matriz 3x3\n {matriz_3x3}\n")

# También puedes usar -1 para que NumPy calcule la dimensión

matriz_3x=vector_2d.reshape(3,-1) ) # numpy calcula que la segunda dimension es 3

print(f"matri 3x? \n{matriz_3x}\n")

vector original 
[0 1 2 3 4 5 6 7 8]

matriz 3x3
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

matri 3x? 
[[0 1 2]
 [3 4 5]
 [6 7 8]]



In [ ]:
#Broadcasting: El mecanismo de NumPy que permite realizar operaciones entre
#arrays de diferentes formas y dimensiones. Las reglas de broadcasting son
#simples: si los arrays tienen la misma forma, se operan elemento por elemento. Si
#no, NumPy intenta "estirar" el array más pequeño para que coincida con el más
#grande

In [61]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([10,20,30])
resultado_broadcating=a+b
print(f"restultado broadcating\n{resultado_broadcating}\n")

# Ejemplo de broadcasting que falla (formas incompatibles)
c=np.array([2,3])
resultado_falla=a+c
print(f"resultado que falla\n{resultado_falla}\n")

restultado broadcating
[[11 22 33]
 [14 25 36]]

resultado que falla
[4 6]

