In [4]:
# Crear un vector 1D de enteros

import numpy as np
lista_1d=[1,2,3,4]
vector=np.array(lista_1d)
print(f"vector:\n{vector}\n") #sale el nombe vector y debajo los datos
print(vector.dtype)

vector:
[1 2 3 4]

int64


In [ ]:
# Crear una matriz 2D de punto flotante
lista_2d=[[1.0,2.0,3.0],[4.0,5.0,6.0]]
matriz=np.array(lista_2d)
print(f"matriz:\n{matriz}\n")
print(f"La forma de la matriz es:{matriz.shape}") #indica la cantidad de filas y columna de la matriz
print(f"tipo de datos{matriz.dtype}") #dtype indica el tipo de datos este caso flotante


matriz:
[[1. 2. 3.]
 [4. 5. 6.]]

La forma de la matriz es:(2, 3)
tipo de datosfloat64


In [19]:
#Arrays de Ceros y Unos:
# Array de ceros de 3x4
ceros=np.zeros((3,4))
print(f"Array Ceros:\n {ceros}  \n")

Array Ceros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]  



In [26]:
# Array de unos de 5 elementos, con tipo de dato entero
unos=np.ones(2,dtype=np.int64)
print(f"Array unos:\n{unos}\n")

Array unos:
[1 1]



In [27]:
# Rangos Numéricos: Crea secuencias de números de forma automática
rango_escalar=np.arange(0,10,2) # De 0 a 10 (excluido), paso de 2
print(f"array con no.arange\n{rango_escalar}\n")

array con no.arange
[0 2 4 6 8]



In [ ]:
# Números espaciados uniformemente
# 5 puntos desde 0 hasta 1 (incluidos)
lineal=np.linspace(0,1,5)
print(f"Array con np.lispace:\n{lineal}\n") #ideal para sistema de coordenadas


Array con np.lispace:
[0.   0.25 0.5  0.75 1.  ]



In [ ]:
#Arrays Aleatorios: NumPy tiene un módulo random muy completo
# Matriz 2x2 de números aleatorios entre 0 y 1 (distribución uniforme
aleatorio=np.random.rand(3,3)
print(f"Matriz Aleatoria uniforme:\n{aleatorio}\n")


Matriz Aleatoria uniforme:
[[0.16956849 0.96198581 0.45510686]
 [0.05642315 0.15474196 0.52619105]
 [0.07141858 0.32401643 0.49228335]]



In [48]:
# Enteros aleatorios en un rango (de 1 a 10, tamaño 3)
enteros_aleatorio=np.random.randint(1,10,size=3) #busca enteros aleatorios la cantidad depende de size
print(f"Enteros aleatorios\n{enteros_aleatorio}\n")

Enteros aleatorios
[9 6 3]



In [52]:
# Números de una distribución normal estándar
normal=np.random.randn(2,3) #toam cualquier entero
print(f"Matriz normal \n{normal}\n")

Matriz normal 
[[-0.08566054 -1.35451151 -0.27014431]
 [ 0.88117271 -0.05018198 -0.76951657]]

