In [1]:
# Crear un vector 1D de enteros

import numpy as np
lista_1d=[1,2,3,4]
vector=np.array(lista_1d)
print(f"vector:\n{vector}\n") #sale el nombe vector y debajo los datos
print(vector.dtype)

vector:
[1 2 3 4]

int64


In [3]:
# Crear una matriz 2D de punto flotante
lista_2d=[[1.0,2.0,3.0],[4.0,5.0,6.0]]
matriz=np.array(lista_2d)
print(f"matriz:\n{matriz}\n")
print(f"La forma de la matriz es:{matriz.shape}") #indica la cantidad de filas y columna de la matriz
print(f"tipo de datos{matriz.dtype}") #dtype indica el tipo de datos este caso flotante


matriz:
[[1. 2. 3.]
 [4. 5. 6.]]

La forma de la matriz es:(2, 3)
tipo de datosfloat64


In [4]:
#Arrays de Ceros y Unos:
# Array de ceros de 3x4
ceros=np.zeros((3,4))
print(f"Array Ceros:\n {ceros}  \n")

Array Ceros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]  



In [5]:
# Array de unos de 5 elementos, con tipo de dato entero
unos=np.ones(5,dtype=np.int64)
print(f"Array unos:\n{unos}\n")

Array unos:
[1 1 1 1 1]



In [7]:
# Rangos Numéricos: Crea secuencias de números de forma automática
rango_escalar=np.arange(0,10,2) # De 0 a 10 (excluido), paso de 2
print(f"array con no.arange\n{rango_escalar}\n")

array con no.arange
[0 2 4 6 8]



In [ ]:
# Números espaciados uniformemente
# 5 puntos desde 0 hasta 1 (incluidos)
lineal=np.linspace(0,1,5)
print(f"Array con np.lispace:\n{lineal}\n") #ideal para sistema de coordenadas


Array con np.lispace:
[0.   0.25 0.5  0.75 1.  ]



In [8]:
#Arrays Aleatorios: NumPy tiene un módulo random muy completo
# Matriz 2x2 de números aleatorios entre 0 y 1 (distribución uniforme
aleatorio=np.random.rand(3,3)
print(f"Matriz Aleatoria uniforme:\n{aleatorio}\n")


Matriz Aleatoria uniforme:
[[0.15908873 0.5198544  0.2965352 ]
 [0.884016   0.66000499 0.25585667]
 [0.06959604 0.31411654 0.32427348]]



In [48]:
# Enteros aleatorios en un rango (de 1 a 10, tamaño 3)
enteros_aleatorio=np.random.randint(1,10,size=3) #busca enteros aleatorios la cantidad depende de size
print(f"Enteros aleatorios\n{enteros_aleatorio}\n")

Enteros aleatorios
[9 6 3]



In [15]:
# Números de una distribución normal estándar
normal=np.random.randn(2,3) #toam cualquier entero
print(f"Matriz normal \n{normal}\n")

Matriz normal 
[[ 0.16286721  0.60623762 -1.8408489 ]
 [-2.54769845 -0.10471996  0.65755522]]



In [22]:
#Indexación Básica: Se accede a los elementos usando los índices entre
#,corchetes, separados por comas para cada dimensión
matriz_1=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(f"matriz original:\n{matriz_1}\n")
# Acceder a un solo elemento (fila 1, columna 2)
print(f"elemento en [1,2] = {matriz_1[1,2]}\n")

# Modificar un elemento
matriz_1[1,2]=90
print(f"matriz modificada\n{matriz_1}\n")

matriz original:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

elemento en [1,2] = 60

matriz modificada
[[10 20 30]
 [40 50 90]
 [70 80 90]]



In [44]:
#Slicing (Corte): Extrae un sub-array de un array existente. La sintaxis
#[inicio:fin:paso] es la misma que en las listas, pero aplicada a cada dimensión

# Todas las filas, pero solo la columna 0 y1
sub_matriz=matriz_1[:,0:2]
print(f"sub matriz columna (0,1) \n{sub_matriz}\n")


sub matriz columna (0,1) 
[[10 20]
 [40 50]
 [70 80]]



In [52]:
## Filas 0 y 1, pero todas las columnas
sub_matriz_2=matriz_1[0:2,:]
print(f"sub matriz fila (0,2)\n{sub_matriz_2}\n")

# Seleccionar la última fila
print(f"seleccon ulima fila \n{matriz_1[-1,:]}")

sub matriz fila (0,2)
[[10 20 30]
 [40 50 90]]

seleccon ulima fila 
[70 80 90]


In [6]:
import numpy as np
## Crear un vector 1D de enteros
lista_1d=[1,22,36,1.4,256]
vector_1d=np.array(lista_1d)
print(f"vector_1d \n{vector_1d}\n")

vector_1d 
[  1.   22.   36.    1.4 256. ]



In [14]:
# Crear una matriz 2D de punto flotante
lista_2d=[[1.4,52,36,0.26],[0,12.3,56,0]]
matriz=np.array(lista_2d)
print(f"matriz\n{matriz}\n")
print(f"la forma de la matriz {matriz.shape}")
print(f"tipo de datos de la matriz {matriz.dtype}")

matriz
[[ 1.4  52.   36.    0.26]
 [ 0.   12.3  56.    0.  ]]

la forma de la matriz (2, 4)
tipo de datos de la matriz float64


In [15]:
# Array de ceros de 3x4
ceros=np.zeros((3,4))
print(f"matriz ceros \n{ceros}\n")

matriz ceros 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]



In [16]:
# Array de unos de 5 elementos, con tipo de dato entero
unos=np.ones(5,dtype=np.int64)
print(f"matriz unos\n{unos}\n")

matriz unos
[1 1 1 1 1]



In [17]:
#Rangos Numéricos: Crea secuencias de números de forma automática.
# Como range() de Python, pero crea un array
rango_escalar=np.arange(0,20,2)
print(f"array np.arange\n{rango_escalar}\n")

array np.arange
[ 0  2  4  6  8 10 12 14 16 18]



In [18]:
# Números espaciados uniformemente
# 5 puntos desde 0 hasta 1 (incluidos)
lineal=np.linspace(0,1,5)
print(f"Array con np.linspace {lineal}")

Array con np.linspace [0.   0.25 0.5  0.75 1.  ]
